task:
  name: Windows build
  container:
    dockerfile: contrib/build-wine/Dockerfile
    cpu: 1
    memory: 2G
  build_script:
    - cd contrib/build-wine
    - ./make_win.sh
  binaries_artifacts:
    path: "contrib/build-wine/dist/*"
  env:
    CIRRUS_WORKING_DIR: /opt/wine64/drive_c/electrum-grs
    CIRRUS_DOCKER_CONTEXT: contrib/build-wine

task:
  name: Android build (Kivy arm64)
  container:
    dockerfile: contrib/android/Dockerfile
    cpu: 2
    memory: 2G
  build_script:
    - ./contrib/android/make_apk.sh kivy arm64-v8a debug
  binaries_artifacts:
    path: "dist/*"

task:
  name: Android build (QML arm64)
  container:
    dockerfile: contrib/android/Dockerfile
    cpu: 8
    memory: 24G
  build_script:
    - ./contrib/android/make_apk.sh qml arm64-v8a debug
  binaries_artifacts:
    path: "dist/*"
  only_if: $CIRRUS_TAG != '' || $CIRRUS_BRANCH == 'ci-qml-beta'

task:
  name: Android build (QML arm32)
  container:
    dockerfile: contrib/android/Dockerfile
    cpu: 8
    memory: 24G
  build_script:
    - ./contrib/android/make_apk.sh qml armeabi-v7a debug
  binaries_artifacts:
    path: "dist/*"
  only_if: $CIRRUS_TAG != '' || $CIRRUS_BRANCH == 'ci-qml-beta'

task:
  name: MacOS build
  macos_instance:
    image: catalina-xcode-11.3.1
  env:
    TARGET_OS: macOS
  install_script:
    - git fetch --all --tags
  build_script:
    - ./contrib/osx/make_osx.sh
  sum_script:
    - ls -lah dist
    - shasum -a 256 dist/*.dmg
  binaries_artifacts:
    path: "dist/*"

task:
  name: AppImage build
  container:
    dockerfile: contrib/build-linux/appimage/Dockerfile
    cpu: 2
    memory: 1G
  build_script:
    - ./contrib/build-linux/appimage/make_appimage.sh
  binaries_artifacts:
    path: "dist/*"
  env:
    CIRRUS_DOCKER_CONTEXT: contrib/build-linux/appimage

task:
  container:
    dockerfile: contrib/build-linux/sdist/Dockerfile
    cpu: 1
    memory: 1G
  build_script:
    - ./contrib/build-linux/sdist/make_sdist.sh
  binaries_artifacts:
    path: "dist/*"
  matrix:
    - name: tarball build
    - name: source-only tarball build
      env:
        OMIT_UNCLEAN_FILES: 1
